#ifndef ERROR_CODES_H
#define ERROR_CODES_H

#define VALID_INPUT 0
#define INVALID_INPUT 1
#define DUPLICATE_KEY 2
#define NULL_INPUT 3
#define CONTAINS_SPECIAL_CHAR 4
#define CONTAINS_LETTER 5
#define EMPTY_STRING 6
#define WHITESPACE_ONLY 7
#define INVALID_AIRPORT_NAME_LENGTH 8
#define NON_ALPHABETIC_AIRPORT_NAME 9


#endif